language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - gzip

install:
    - "export PATH=$PWD/bin:$PATH"
#    - "cpanm --quiet --notest File::Which"

script:
    - "trencha --version"
    - "trencha --help"
    - "cd perl5/Biotool && for M in *.pm ; do perl $M ; done"

