language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - gzip

install:
    - "export PATH=$PWD/bin:$PATH"
#    - "cpanm --quiet --notest File::Which"

script:
    - "perl-biotool --version"
    - "perl-biotool --help"
    - "perl-biotool --check dummy"
    - "perl-biotool dummy"
    - "perl-biotool |& grep 'Need at least 1'"
    - perl-biotool dummy --myinc --myinc --myinc |& grep "'myinc' => 3"
    - perl-biotool dummy --myint -42 |& grep "myint' => '-42'"
    - "! perl-biotool file1 file2"
    - "cd perl5/Biotool && for M in *.pm ; do perl $M ; done"

